local root="/opt/freesurfer"
local mnip5lib=pathJoin(root, "mni/share/perl5")
local mnibin=pathJoin(root, "mni/bin")
conflict("minc")
setenv("OS", "Linux")
setenv("FREESURFER_HOME", root)
setenv("FS_OVERRIDE", 0)
setenv("FSFAST_HOME", pathJoin(root, "fsfast"))
-- setenv("SUBJECTS_DIR", pathJoin(root, "subjects"))
setenv("FUNCTIONALS_DIR", pathJoin(root, "sessions"))
setenv("MINC_BIN_DIR", mnibin)
setenv("MNI_DIR", pathJoin(root, "mni"))
setenv("MINC_LIB_DIR", pathJoin(root, "mni/lib"))
setenv("MNI_DATAPATH", pathJoin(root, "mni/data"))
setenv("LOCAL_DIR", pathJoin(root, "local"))
setenv("FSF_OUTPUT_FORMAT", "nii.gz")
setenv("MNI_PERL5LIB", mnip5lib)
prepend_path("PERL5LIB", mnip5lib)
prepend_path("PATH", mnibin)
prepend_path("PATH", pathJoin(root, "tktools"))
prepend_path("PATH", pathJoin(root, "bin"))
prepend_path("PATH", pathJoin(root, "fsfast", "bin"))
setenv("FIX_VERTEX_AREA", "")
